version: '3'

volumes:
  mysql_data:
services:
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - './api:/myapp'
      - './api/vendor/bundle:/myapp/vendor/bundle'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - './front:/user/src/app'
    command: sh -c "yarn start"
    ports:
      - '8000:3000'
    tty: true
    stdin_open: true
