version: "3"

services:
  prod:
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    command: "bundle exec pumactl start"
    volumes:
      - ./api:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - '3000:3000'
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: mysqld --innodb_use_native_aio=0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - prod
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - './front:/user/src/app'
    environment:
      - WDS_SOCKET_PORT=0
    command: sh -c "yarn start"
    ports:
      - '8000:3000'
volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:
