version: '3'

services:
  prod:
    build: 
      context: ./api/
      dockerfile: Dockerfile.prod
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./api:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - '80:80'
    depends_on:
      - prod
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: