version: '3'

volumes:
  mysql_data:
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - '../api:/myapp'
      - '../api/vendor/bundle:/myapp/vendor/bundle'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: mysqld --innodb_use_native_aio=0
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  front:
    build:
      context: ../front/
      dockerfile: Dockerfile
    volumes:
      - '../front:/user/src/app'
    environment:
      - WDS_SOCKET_PORT=0
    command: sh -c "yarn start"
    ports:
      - '8000:3000'
    tty: true
    stdin_open: true
