default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  usernme: root
  password: password
  host: db
  timeout: 5000

development:
  <<: *default
  database: development_gahack_db

test:
  <<: *default
  database: test_gahack_db

production:
  <<: *default
  database: cld0v2gnc00339tryar3y96r9
  username: cld0v2gnb00319try4gjq35y8
  password: <%= ENV['GAHACK_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
