default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  usernme: root
  password: password
  host: db
  timeout: 5000

development:
  <<: *default
  database: development_gahack_db

test:
  <<: *default
  database: test_gahack_db

production:
  <<: *default
  database: production_gahack_db
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
