require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'bundle/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
