source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.4'
gem 'rails', '~> 6.1.7'
gem 'puma', '~> 5.0'
gem 'mysql2', '~> 0.5'


# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

gem 'rack-cors'

# ログイン機能
gem 'devise'
gem 'devise_token_auth'

# 画像アップロード機能を実装
gem 'carrierwave', '~> 2.0'
gem 'mini_magick'

# シリアライザー（JSON整形用gem）
gem 'active_model_serializers'

# S3設定用
gem 'fog-aws'

# 管理画面用Gem
gem 'activeadmin'
gem 'sassc-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'dotenv-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "letter_opener_web"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
